from weight.curves.male_years import WeightCurveMaleYears
from weight.curves.male_months import WeightCurveMaleMonths
from weight.curves.female_years import WeightCurveFemaleYears
from weight.curves.female_months import WeightCurveFemaleMonths
